import Song from '../../components/Song'
import Head from 'next/head'



export default function SongPage({ song }) {
  return (
    <div>
        <Head>
            <title>{song.title}</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href={song.album.picture} />
        </Head>
        <Song song={song} />
    </div>
  )
}

/**
* 
* @param {import('next').GetServerSidePropsContext} context
* @returns
*/
export async function getServerSideProps(context) {
    const res = await fetch(`${process.env.BASE_URL}/api/song/${context.params.id}`)
    const song = await res.json()

    return {
        props: {
           song
        }
    }
}