import Navbar from '../../components/Navbar'
import Head from 'next/head'
import SongCard from '../../components/SongCard'


export default function SongIndex({ songs }) {
  return (
    <div>
      <Head>
          <title>Song List | Songs Collection</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
      </Head>
        <Navbar />
            {songs.map((song) => (
              <SongCard key={song.id} song={song} />
            ))}
    </div>
  )
}

/**
* 
* @param {import('next').GetServerSidePropsContext} context
* @returns
*/
export async function getServerSideProps(context) {
    const res = await fetch(`${process.env.BASE_URL}/api/song`)
    const songs = await res.json()

    return {
        props: {
           songs
        }
    }
}